### ISSUE TITLE
Bug in `to_tableau` function for SPP gates

### ISSUE THREAD

**Issue by NnktYoshioka** [quantumlib/Stim#846] opened 2024-10-28 05:35 UTC
It seems that the `stim.Circuit.to_tableau` is not reflecting the presence of SPP gate now (tried in v1.13.0 and v1.14.0).
For instance when I run
```python
print(stim.Circuit("""
H 0
SPP Z0
""").to_tableau())

# not correct
#stim.Tableau.from_conjugated_generators(
#    xs=[
#        stim.PauliString("+Z"),
#    ],
#    zs=[
#        stim.PauliString("+X"),
#    ],
#)

print(stim.Circuit("""
H 0
S 0
""").to_tableau())

# as expected
#stim.Tableau.from_conjugated_generators(
#    xs=[
#        stim.PauliString("+Z"),
#    ],
#    zs=[
#        stim.PauliString("+Y"),
#    ],
#)
```
The output did not change when I choose `SPP X0` or `SPP Y0`, so I suspect that `to_tableau` is ignoring `SPP` gates.

I confirmed that SPP gates are properly working on`TableauSimulator`, by, e.g., running the following:
```python
tsim = stim.TableauSimulator()
tsim.do(stim.Circuit("""
H 0
SPP Z0
"""))

print(tsim.canonical_stabilizers())

#[stim.PauliString("+Y")]
```

**Comment by Strilanc** [comment] 2024-10-28 05:48
Good catch. It seems like this is caused by SPP not being marked as a unitary gate, so the method skips right over it (as part of the logic for optionally ignoring non-unitary gates).

**Comment by Strilanc** [comment] 2024-10-28 06:04
I created a fix (https://github.com/quantumlib/Stim/pull/847). Around a half hour after that PR is merged, you should be able to `pip install stim~=1.15.dev` and then `stim.Circuit("SPP X0").to_tableau()` should work.

**Comment by NnktYoshioka** [comment] 2024-10-28 08:34
Thanks for the superprompt fix! I pip-installed the PR and confirmed that it is working properly.

**Comment by Strilanc** [comment] 2024-10-28 21:06
...what? The fix isn't pushed yet!

**Closed** 2024-10-28 22:26 UTC
