### ISSUE TITLE
getting_started.ipynb guide problem with surface code

### ISSUE THREAD

**Issue by ronf6co** [quantumlib/Stim#187] opened 2022-01-16 13:57 UTC
In the last section of [Getting started file](https://github.com/quantumlib/Stim/blob/main/doc/getting_started.ipynb) it seems that the logical errors counter is assuming that the correction in surface codes must find the exact errors that happened in order to fix them.
But this is not the case for surface code. as long as find the right path between 2 vertexes that caused the error, you can apply correction even if you do not know the exact path, and can just apply any path between them.
Therefore, difference between original error and assumed error by Minimum Weight Matching, is not the key to show the rate of ligicals errors.

You can read about it in [This Notes](http://www.thp.uni-koeln.de/kastoryano/ExSheets/Notes_v9.pdf) page 45 for example

**Comment by Strilanc** [comment] 2022-01-17 02:05
Where do you think that it's making this assumption? I can confirm it's not making that assumption, but I'm interested to know any misleading sentences.

The reason it isn't making this assumption is because all that's really being counted under the hood is how many times the matched paths go over an edge marked as flipping the error frame. Specifically it cares whether the count is even or odd. The marked edges form 2d surfaces splitting the 3d matching graph into two connected components. So it doesn't matter what path is taken through the graph when matching detection events, only whether that path crosses between the two connected components and even or odd number of times.

In more complex situations, such as performing S gates using twists, it may no longer be the case that there are two connected components. But the path independence property will still hold, though often only for paths with lengths less than the code distance.

**Comment by ronf6co** [comment] 2022-01-18 14:07
It seems that for surfacce code benchmarking, you are using:
```
def count_logical_errors(circuit: stim.Circuit, num_shots: int) -> int:
    shots = circuit.compile_detector_sampler().sample(num_shots, append_observables=True)

    detector_parts = shots[:, :circuit.num_detectors]
    actual_observable_parts = shots[:, circuit.num_detectors:]
    predicted_observable_parts = predict_observable_errors_using_pymatching(circuit, detector_parts)

    num_errors = 0
    for actual, predicted in zip(actual_observable_parts, predicted_observable_parts):
        if not np.array_equal(actual, predicted):
            num_errors += 1
    return num_errors
```
which is using the following function that is trying to predict the error that happened using the minimum weight method.
```
def predict_observable_errors_using_pymatching(circuit: stim.Circuit,
                                               det_samples: np.ndarray,
                                               ) -> np.ndarray:
    """Turn detection events into predicted observable errors."""
    error_model = circuit.detector_error_model(decompose_errors=True)
    matching_graph = detector_error_model_to_pymatching_graph(error_model)

    num_shots = det_samples.shape[0]
    num_obs = circuit.num_observables
    num_dets = circuit.num_detectors
    assert det_samples.shape[1] == num_dets

    predictions = np.zeros(shape=(num_shots, num_obs), dtype=np.bool8)
    for k in range(num_shots):
        expanded_det = np.resize(det_samples[k], num_dets + 1)
        expanded_det[-1] = 0
        predictions[k] = matching_graph.decode(expanded_det)
    return predictions
```

this function might find an error chain that happened and is different from the real original error, but also a possible solution.
and then `count_logical_errors` will see that they are different, and claim it to be an error.

What am I missing? I also might be wrong, but I actually did not understand how your answer match what's happening in the code

**Comment by Strilanc** [comment] 2022-01-18 18:33
All that function is doing is running a simulation, separating out the detection event data and the observable-flipped data, then asking the decoder to predict the observable-flipped data from the detection event data.

Maybe the thing you're missing is that in a memory experiment there's **only one** observable bit per shot? It's only predicting whether or not the final logical measurement of the observable was inverted or not, not separating the observable into many parts which must be individually correct.

In more complex experiments there may be multiple observables. For example an experiment that prepares a Bell pair, preserves it, and then measures it, would have two observable bits instead of one. And a 7-to-1 S state distillation factory would have perhaps 8 observables.

**Comment by Strilanc** [comment] 2022-01-25 09:50
Closing this as working as intended, unless there's some specific improvement to make to the docs.

**Closed by Strilanc** 2022-01-25 09:50 UTC
