### ISSUE TITLE
'pip install stim' failing with error 'src/stim.cc:17:10: fatal error: 'stim.h' file not found'

### ISSUE THREAD

**Issue by OzYossarian** [quantumlib/Stim#225] opened 2022-04-11 10:29 UTC
I'm a novice with these sorts of things, so any help appreciated. I'm on a Mac running Monterey 12.1. I have a conda environment activated, and from inside that I write 'pip install stim' in the terminal. Here's the output:

```
(FaultTolerantQPU) teague@Alexs-MacBook-Air FaultTolerantQPU % pip install stim              
Collecting stim
  Using cached stim-1.8.0.tar.gz (164 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniconda/base/envs/FaultTolerantQPU/lib/python3.10/site-packages (from stim) (1.22.3)
Building wheels for collected packages: stim
  Building wheel for stim (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for stim (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      /private/var/folders/6x/zhywbg6x4h5grk1nhzkr3l8c0000gn/T/pip-build-env-k7_z1q49/overlay/lib/python3.10/site-packages/setuptools/_distutils/extension.py:131: UserWarning: Unknown Extension options: 'headers'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating python_build_stim
      creating python_build_stim/lib.macosx-11.1-arm64-cpython-310
      creating python_build_stim/lib.macosx-11.1-arm64-cpython-310/stim
      copying glue/python/src/stim/__init__.py -> python_build_stim/lib.macosx-11.1-arm64-cpython-310/stim
      running build_ext
      building 'stim._stim_march_polyfill' extension
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/circuit
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/dem
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/gen
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/io
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/mem
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/py
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/simulators
      creating python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim/stabilizers
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/FaultTolerantQPU/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniconda/base/envs/FaultTolerantQPU/include -arch arm64 -I/private/var/folders/6x/zhywbg6x4h5grk1nhzkr3l8c0000gn/T/pip-build-env-k7_z1q49/overlay/lib/python3.10/site-packages/pybind11/include -Isrc -I/opt/homebrew/Caskroom/miniconda/base/envs/FaultTolerantQPU/include/python3.10 -c src/stim.cc -o python_build_stim/temp.macosx-11.1-arm64-cpython-310/src/stim.o -std=c++11 -fno-strict-aliasing -O3 -g0 -DVERSION_INFO=1.8.0 -mno-avx2 -DSTIM_PYBIND11_MODULE_NAME=_stim_march_polyfill
      clang: warning: argument unused during compilation: '-mno-avx2' [-Wunused-command-line-argument]
      src/stim.cc:17:10: fatal error: 'stim.h' file not found
      #include "stim.h"
               ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for stim
Failed to build stim
ERROR: Could not build wheels for stim, which is required to install pyproject.toml-based projects
```

I've tried upgrading my pip - no joy. When I type 'clang --version' I get:

```
(FaultTolerantQPU) teague@Alexs-MacBook-Air FaultTolerantQPU % clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

What else can I try / what other info can I give that might be useful? Thanks in advance!

**Comment by Strilanc** [comment] 2022-04-11 17:49
I wasn't expecting to be able to, but I'm able to reproduce this by using `pip install stim --no-binary stim`. It produces a very useful warning saying that the `headers` argument given in `setup.py` is not recognized. Which would explain why it's not including all the headers files I told it to.

Shouldn't be too bad to fix, although it might result in headers files being packaged into the binary wheels (ugh). I thought this case was being verified by cibuildwheels during the continuous integration testing. I'll have to add a check to verify it to ensure it doesn't break again.

**Comment by Strilanc** [comment] 2022-04-11 17:53
A secondary issue here is that you're installing the sdist instead of a binary wheel. It's possible just bumping the version of cibuildwheel is sufficient.

**Comment by Strilanc** [comment] 2022-04-11 17:56
@OzYossarian when you install numpy, does it also build from source, or does it just download something in ~10s and move on? If it does download something, what is the filename of what it downloaded? For example `numpy-1.22.3-cp310-cp310-win_amd64.whl`.

**Comment by Strilanc** [comment] 2022-04-12 22:01
Okay, osx arm64; I am in fact not building that. Hopefully bumping cibuildwheel fixes that since they do list it as supported.

**Comment by OzYossarian** [comment] 2022-04-13 08:46
Sweeeeet, thanks for the fix!

**Comment by Strilanc** [comment] 2022-04-13 20:25
It turns out cibuildwheel (on github actions) does not support building those wheels :/ . Maybe I should just expense an M2 mac...

Anyways, I'll have the stim.h thing fixed.

**Comment by Strilanc** [comment] 2022-04-13 20:29
The fix is merged. Once it passes CI on main it will be automatically deployed as a timestamped dev version to pypi. I'll let you know what to install when it's out, to verify it worked.

**Comment by Strilanc** [comment] 2022-04-14 04:55
Try `pip install stim==1.9.dev1649881693` and see if that builds.

**Comment by Strilanc** [comment] 2022-04-19 06:32
@OzYossarian any updates on if it worked?

**Comment by OzYossarian** [comment] 2022-04-19 07:57
Sorry for the slow reply - yes it did! Thanks very much for the fix. Output is:

```
(FaultTolerantQPU) teague@Alexs-MacBook-Air FaultTolerantQPU % pip install stim==1.9.dev1649881693
Collecting stim==1.9.dev1649881693
  Downloading stim-1.9.dev1649881693.tar.gz (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.4/214.4 KB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniconda/base/envs/FaultTolerantQPU/lib/python3.10/site-packages (from stim==1.9.dev1649881693) (1.22.3)
Building wheels for collected packages: stim
  Building wheel for stim (pyproject.toml) ... done
  Created wheel for stim: filename=stim-1.9.dev1649881693-cp310-cp310-macosx_11_0_arm64.whl size=2166275 sha256=4b548bef4851a5bd362afd8e330416bea52b58826b4432c8f8023dc0475aede1
  Stored in directory: /Users/teague/Library/Caches/pip/wheels/82/83/bc/b3ec70304c739c55ce7294c54cfcb3cdcae7abad86afec0779
Successfully built stim
Installing collected packages: stim
Successfully installed stim-1.9.dev1649881693

```

Took about 4 minutes - don't know if that's slower than normal, but either way it's successfully installed. Thanks!

**Comment by Strilanc** [comment] 2022-04-19 07:58
Great!

**Closed by Strilanc** 2022-04-19 07:58 UTC
